development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: "rediss://:p62df3b83168720303eeb439f01a7e24880531fc1af86e69aeab500a2ccb093e4@ec2-52-86-129-199.compute-1.amazonaws.com:9860" # <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: smart_home_api_production
